In [1]:
import numpy as np

A = np.array([[0.0, 0.0], [1.0, 0.0], [0.0, 1.0], [1.0, 1.0]])
B = np.asarray([[4.0, 0.0], [1.0, 1.0], [2.0, 2.0], [2.0, 3.0]])

In [2]:
a_min_b = A - B
np.sqrt(np.einsum("ij,ij->i", a_min_b, a_min_b))

array([4.        , 1.        , 2.23606798, 2.23606798])

In [3]:
np.linalg.norm(A - B, axis=1)

array([4.        , 1.        , 2.23606798, 2.23606798])

In [4]:
d_all = np.sqrt(np.einsum("ij->i", (A - B) ** 2))
d_all

array([4.        , 1.        , 2.23606798, 2.23606798])